# **Assignment 1 - Working with NumPy**

**1. Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:**

  a. Calculate the sum, mean, median, and standard deviation of the elements in the array.  
  b. Find the indices of elements greater than 10 in the array.


In [4]:
import numpy as np

# Create a 1D NumPy array with integers from 1 to 20
arr = np.arange(1, 21)

# a. Calculate sum, mean, median, and standard deviation
arr_sum = np.sum(arr)
arr_mean = np.mean(arr)
arr_median = np.median(arr)
arr_std = np.std(arr)

# b. Find indices of elements greater than 10
indices_greater_than_10 = np.where(arr > 10)

# Display results
print("Array:", arr)
print("Sum:", arr_sum)
print("Mean:", arr_mean)
print("Median:", arr_median)
print("Standard Deviation:", arr_std)
print("Indices of elements > 10:", indices_greater_than_10)


Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


**2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.**
  
  a. Print the array.  
  b. Find the transpose of the array.  
  c. Calculate the row-wise and column-wise sums of the array.  




In [5]:
import numpy as np

# Create a 2D NumPy array of shape 4x4 with numbers from 1 to 16
arr = np.arange(1, 17).reshape(4, 4)

# a. Print the array
print("Original Array:\n", arr)

# b. Find the transpose of the array
arr_transpose = arr.T
print("\nTranspose of Array:\n", arr_transpose)

# c. Calculate row-wise and column-wise sums
row_sum = np.sum(arr, axis=1)     # Sum across columns (row-wise)
col_sum = np.sum(arr, axis=0)     # Sum across rows (column-wise)

print("\nRow-wise Sum:", row_sum)
print("Column-wise Sum:", col_sum)


Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Transpose of Array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

Row-wise Sum: [10 26 42 58]
Column-wise Sum: [28 32 36 40]


**3. Create two 3 X 3 arrays filled with random integers between 1 and 20.**

  a. Perform element-wise addition, subtraction, and multiplication.  
  b. Compute the dot product of the two arrays.  




In [6]:
import numpy as np

# Create two 3x3 arrays filled with random integers between 1 and 20
arr1 = np.random.randint(1, 21, size=(3, 3))
arr2 = np.random.randint(1, 21, size=(3, 3))

# Display arrays
print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)

# a. Element-wise addition, subtraction, and multiplication
add_result = arr1 + arr2
sub_result = arr1 - arr2
mul_result = arr1 * arr2

print("\nElement-wise Addition:\n", add_result)
print("\nElement-wise Subtraction:\n", sub_result)
print("\nElement-wise Multiplication:\n", mul_result)

# b. Compute the dot product of the two arrays
dot_result = np.dot(arr1, arr2)
print("\nDot Product (Matrix Multiplication):\n", dot_result)


Array 1:
 [[ 7 20 10]
 [ 8 19  5]
 [10 20  7]]

Array 2:
 [[ 1 19 14]
 [13  1  9]
 [17 11 16]]

Element-wise Addition:
 [[ 8 39 24]
 [21 20 14]
 [27 31 23]]

Element-wise Subtraction:
 [[ 6  1 -4]
 [-5 18 -4]
 [-7  9 -9]]

Element-wise Multiplication:
 [[  7 380 140]
 [104  19  45]
 [170 220 112]]

Dot Product (Matrix Multiplication):
 [[437 263 438]
 [340 226 363]
 [389 287 432]]


**4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.**

In [7]:
import numpy as np

# Create a 1D array of size 12
arr = np.arange(1, 13)

# Reshape into a 3x4 2D array
arr_2d = arr.reshape(3, 4)

print("Original 2D Array:\n", arr_2d)

# Slice: first two rows and last two columns
sliced_arr = arr_2d[:2, -2:]

print("\nSliced Array (First two rows & last two columns):\n", sliced_arr)


Original 2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced Array (First two rows & last two columns):
 [[3 4]
 [7 8]]
